config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :proyectos do
	member do
		post 'deleteportada'
	end
    resources :fotos, only: [:new, :create, :destroy]
  end
  root 'proyectos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foto.rb
class Foto < ApplicationRecord
  belongs_to :proyecto
  validates :src, presence: true
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many :fotos, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]
  before_action :set_proyecto

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
	result = Cloudinary::Uploader.upload(foto_params[:src])
	@foto = @proyecto.fotos.build(foto_params) do |t|
        t.src = result['url']
		t.public_id = result['public_id']
    end
	if @foto.save
      redirect_to @proyecto
    else
      render :new
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
	Cloudinary::Api.delete_resources([@foto.public_id])
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to @proyecto, notice: 'Foto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
	def set_proyecto
	  @proyecto = Proyecto.find(params[:proyecto_id])
	end
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:descripcion, :src, :id, :es_portada)
    end
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy, :deleteportada]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
	@fotos = @proyecto.fotos
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end
  
  # POST /proyectos/1/deleteportada
  def deleteportada
	Cloudinary::Api.delete_resources([@proyecto.portada_id])
	@proyecto.portada = ''
	@proyecto.portada_id = ''
	respond_to do |format|
	  if @proyecto.save
		  if @proyecto.portada.blank?
			format.html { redirect_to @proyecto, notice: 'Portada was successfully deleted.' }
			format.json { render :show, status: :created, location: @proyecto }
		  end
	  end
	end
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
	if !proyecto_params[:portada].blank?
		result = Cloudinary::Uploader.upload(proyecto_params[:portada])
		@proyecto = Proyecto.new(proyecto_params) do |t|
			t.portada = result['url']
			t.portada_id = result['public_id']
		end
	end
    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
	id = @proyecto.id
	pp = proyecto_params
	if !proyecto_params[:portada].blank?
		result = Cloudinary::Uploader.upload(proyecto_params[:portada])
		pp[:portada] = result['url']
		pp[:portada_id] = result['public_id']
	end
	puts(pp[:portada_id])
	respond_to do |format|
      if @proyecto.update(pp)
        format.html { redirect_to proyecto_path(id), notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
	if !@proyecto.portada.blank?
		Cloudinary::Api.delete_resources([@proyecto.portada_id])
	end
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      params.require(:proyecto).permit(:titulo, :tramite, :ubicacion, :descripcion, :fecha, :portada, :portada_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/fotos/_form.html.erb
<%= form_with(model:[@proyecto, foto], local: true, :html => {:multipart => true}) do |form| %>
  <% if foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :foto_descripcion %>
  </div>

  <div class="field">
    <%= form.label :src %>
	 <%= form.file_field :src %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing Foto</h1>

<%= render 'form', foto: @foto %>

<%= link_to 'Back', proyecto_path(@proyecto) %>

app/views/fotos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fotos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Src</th>
      <th>Proyecto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= foto.descripcion %></td>
        <td><%= image_tag(foto.src) %></td>
        <td><%= foto.proyecto %></td>
        <td><%= link_to 'Show', foto %></td>
        <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
        <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New Foto</h1>

<%= render 'form', foto: @foto, proyecto: @proyecto %>

<%= link_to 'Back', proyecto_path(@proyecto) %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @foto.descripcion %>
</p>

<p>
  <strong>Src:</strong>
  <%= @foto.src %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= @foto.proyecto %>
</p>

<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProArq</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto, local: true, :html => {:multipart => true}) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% proyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :proyecto_titulo %>
  </div>

  <div class="field">
    <%= form.label :tramite %>
    <%= form.text_field :tramite, id: :proyecto_tramite %>
  </div>

  <div class="field">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion, id: :proyecto_ubicacion %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :proyecto_descripcion %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha, id: :proyecto_fecha %>
  </div>

	<% if @proyecto.portada.blank?%>
	  <div class="field">
		<%= form.label :portada %>
		<%= form.file_field :portada %>
	  </div>
	 <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Editing Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>
<% if !(@proyecto.portada.blank?) %>
	<img src=<%= @proyecto.portada%>>
	<%= button_to 'Delete Portada', deleteportada_proyecto_path(@proyecto.id), method: :post %>
<% end %>
<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<p id="notice"><%= notice %></p>

<!-- Page Content -->
<div class="container">
	<div class="row" >
		<div class="col-md-3">
			<a href=<%= proyectos_path %>>
				<img class="img-responsive" src="http://res.cloudinary.com/proarq/image/upload/v1501698086/Logo_z6rlzd.png" alt="">
			</a>
		</div>
		<div class="col-md-9">
			<!-- Page Header -->
			<div class="row">
				<div class="col-lg-12">
					<h1 class="page-header">Proyectos</h1>
				</div>
			</div>
			<!-- /.row -->
			
			<% @proyectos.each_with_index do |proyecto, index| %>
				<% if index % 3 == 0 %>
					<!-- Projects Row -->
					<div class="row">
				<% end %>
				<div class="col-md-4 portfolio-item">
					<a href=<%= proyecto_path(proyecto.id) %>>
						<img class="img-responsive" src=<%= proyecto.portada%> alt="">
					</a>
					<h3>
						<a href=<%= proyecto_path(proyecto.id) %>>
							<%= proyecto.titulo %>
						</a>
					</h3>
					<p><%= proyecto.descripcion %></p>
					<% if user_signed_in? %>
						<%= link_to 'Edit', edit_proyecto_path(proyecto) %>
						<%= link_to 'Destroy', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %>
					<% end %>
				</div>
				<% if index % 3 == 0 %>
					</div>
					<!-- /.row -->
				<% end %>
			 <% end %>
			 <br>
			<% if user_signed_in? %>
				<%= link_to 'New Proyecto', new_proyecto_path %>
			<% end %>
		</div>
	</div>
</div>

app/views/proyectos/new.html.erb
<h1>New Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Back', proyectos_path %>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

	<!-- Portfolio Item Heading -->
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">
				<%= @proyecto.titulo%>
			</h1>
		</div>
	</div>
	<!-- /.row -->

	<!-- Portfolio Item Row -->
	<div class="row">

		<div class="col-md-8">
			<img class="img-responsive" src=<%= @proyecto.portada%> alt="">
		</div>

		<div class="col-md-4">
			<h3>Descripcion</h3>
			<p><%= @proyecto.descripcion %></p>
			<h3>Detalles</h3>
			<ul>
				<li>Trámite: <%= @proyecto.tramite %></li>
				<li>Ubicación: <%= @proyecto.ubicacion %></li>
				<li>Fecha: <%= @proyecto.fecha %></li>
			</ul>
		</div>

	</div>
	<!-- /.row -->
	
	<hr>
	
	<!-- Project images Row -->
	<% @fotos.each_with_index do |foto, index| %>
		<% if index % 4 == 0 %>
			<!-- Projects Row -->
			<div class="row">
		<% end %>
		<div class="col-sm-3 col-xs-6">
			<div class="container-image-overlay">
				<img class="img-responsive portfolio-item" src=<%=foto.src%> alt="">
				<div class="overlay">
					<div class="text-overlay"><%=foto.descripcion%></div>
				</div>
			</div>
			<% if user_signed_in? %>
				<%= link_to 'Destroy', proyecto_foto_path(@proyecto.id, foto.id), method: :delete %>
			<% end %>
		</div>
		<% if index % 4 == 0 %>
			</div>
			<hr>
			<!-- /.row -->
		<% end %>
	<% end %>
	<% if user_signed_in? %>
		<%= link_to new_proyecto_foto_path(@proyecto) do %>
			<p>Agregar nueva imagen...</p>
		<% end %>
		<%= link_to 'Editar proyecto', edit_proyecto_path(@proyecto) %> |
		<%= link_to 'Volver', proyectos_path %>
	<% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'ProArq', root_path, class: 'navbar-brand' %>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li>
					<a href="#">Nostros</a>
				</li>
				<li>
					<a href="#">Contacto</a>
				</li>
				<li>
					<% if user_signed_in? %>
						<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>